matrix:
  include:
    - language: node_js
      node_js:
        - "12.14.0"
      script: yarn
    - language: android
      jdk: oraclejdk8
      dist: trusty
      android:
        components:
          - build-tools-29.0.2
          - android-29
          - extra-android-m2repository
      script: ls
